openapi: 3.0.0
info:
  title: GovTech Product Scorecard API
  version: 1.0.0
  description: |
    API for managing product metrics and reports.

    ## Authentication
    To authenticate with the API, you need to:
    1. Log in to the GovTech Product Scorecard site
    2. Go to your user profile
    3. Generate an API key
    4. Use your email and API key for Basic Authentication

    Example:
    ```
    # Your email and API key
    email = "your_email@tech.gov.sg"
    api_key = "your-api-key-here"

    # Combine them with a colon
    credentials = email + ":" + api_key

    # Base64 encode the credentials
    encoded_credentials = base64_encode(credentials)

    # Add to Authorization header
    headers = {
        "Authorization": "Basic " + encoded_credentials
    }
    ```

servers:
  - url: /api/v1
    description: API base URL

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
      description: |
        Basic authentication using your GovTech Product Scorecard email and API key.
        The API key can be generated in your user profile on the Product Scorecard site.
        Format: `email:api_key` base64 encoded

  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        slug:
          type: string
        govtechProductID:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        status:
          type: string
        logoURL:
          type: string
          nullable: true
        division:
          type: string
        programme:
          type: string
          nullable: true
        managers:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              email:
                type: string

    Error:
      type: object
      properties:
        error:
          type: string

    MetricUpdate:
      type: object
      properties:
        name:
          type: string
        amount:
          type: number

    UpdateMetricsRequest:
      type: object
      properties:
        period:
          type: string
          description: The reporting period in the format "Q{quarter} {year}" (e.g. "Q3 2024", "Q4 2024")
          example: "Q3 2024"
        metrics:
          type: array
          items:
            $ref: '#/components/schemas/MetricUpdate'

    UpdateMetricsResponse:
      type: object
      properties:
        period:
          type: string
        product:
          type: string
        metrics:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              amount:
                type: number

paths:
  /products:
    get:
      summary: Get all products
      security:
        - BasicAuth: []
      responses:
        '200':
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /products/{productSlug}:
    post:
      summary: Update product metrics
      security:
        - BasicAuth: []
      parameters:
        - name: productSlug
          in: path
          required: true
          schema:
            type: string
            description: The URL-friendly slug of the product (e.g. from products.tech.gov.sg/products/en-trust, the slug would be "en-trust")
            example: "en-trust"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMetricsRequest'
      responses:
        '201':
          description: Metrics updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateMetricsResponse'
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        path:
                          type: string
                        message:
                          type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string 